name: hsm-dash

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - geopandas
  - pyproj
  - pandas
  - rioxarray
  - xarray
  - numpy
  - pyarrow
  - matplotlib 
  - ipyleaflet
  - pip
  - pip:
    - shiny
    - shinyswatch
    - shinywidgets
    - python-dotenv
    - fsspec
    - gcsfs
    - rsconnect-python
