species_name_mapping = {
    "Pipistrellus pipistrellus": "Common Pipistrelle",
    "Pipistrellus pygmaeus": "Soprano Pipistrelle",
    "Plecotus auritus": "Brown Long Eared",
    "Myotis mystacinus": "Whiskered",
    "Nyctalus noctula": "Noctule",
    "Myotis daubentonii": "Daubenton's",
    "Myotis nattereri": "Natterer's",
    "Nyctalus leisleri": "Leisler's",
    "Myotis brandtii": "Brandt's",
}


feature_names = {
    "climate_stats_wind_ann_avg" : "Wind",
    "dtm-100m_LIDAR_Composite_2m_DTM_2022_Elevation" : "Elevation",
    "climate_stats_temp_ann_avg" : "Temperature",
    "climate_stats_prec_ann_avg" : "Precipitation",
    "bioclim_bioclim_15": "Bioclim 15 (Precipitation Seasonality)",
    "os-distance-to-feature_distance_to_buildings" : "Distance to Buildings",
    "terrain-stats_slope" : "Slope",
    "terrain-stats_twi" : "Topographic Wetness Index",
    "bioclim_bioclim_9" : "Bioclim 9 (Mean Temperature of Driest Quarter)",
    "ceh-land-cover-100m_Arable" : "Arable Cover",
    "ceh-land-cover-100m_Improved grassland" : "Improved Grassland",
    "veg-height-100m_veg_height_max" : "Vegetation Height",
    "os-feature-cover-100m_water" : "Water Cover",
    "terrain-stats_aspect_northness_slope" : "North Aspect * Slope",
    "terrain-stats_aspect_eastness_slope" : "East Aspect * Slope",
    "terrain-stats_tpi" : "Topographic Position Index",
    "ceh-land-cover-100m_Wetland" : "Wetland Cover",
    "os-feature-cover-100m_major_roads" : "Major Roads Cover",
    "ceh-land-cover-100m_Upland Heathland" : "Upland Heathland Cover",
    "ceh-land-cover-100m_Suburban" : "Suburban Cover",
    "ceh-land-cover-100m_Grassland" : "Grassland Cover",
    "os-distance-to-feature_distance_to_major_roads" : "Distance to Major Roads",
    "ceh-land-cover-100m_Urban" : "Urban Cover",
    "os-distance-to-feature_distance_to_water" : "Distance to Water",
    "ceh-land-cover-100m_Coniferous woodland" : "Coniferous Woodland Cover",
    "ceh-land-cover-100m_Arable_500m" : "Arable Cover (500m)",
    "veg-height-100m_veg_height_max_500m" : "Vegetation Height (500m)",
    "os-feature-cover-100m_water_500m" : "Water Cover (500m)",
    "ceh-land-cover-100m_Grassland_500m" : "Grassland Cover (500m)",
    "ceh-land-cover-100m_Wetland_500m" : "Wetland Cover (500m)",
    "ceh-land-cover-100m_Suburban_500m" : "Suburban Cover (500m)",
    "ceh-land-cover-100m_Urban_500m" : "Urban Cover (500m)",
    "ceh-land-cover-100m_Improved grassland_500m" : "Improved Grassland (500m)",
    "ceh-land-cover-100m_Coniferous woodland_500m" : "Coniferous Woodland (500m)",
}
